AMQP_URI: amqp://guest:guest@127.0.0.1:5672//

MONGO_CONFIG:
  sensorcmd:
    DB_NAME: sensorcmd
    DB_HOST: 192.168.111.149:27019
    CACHE_HOST: 192.168.111.5:6371
  citybms:
    DB_NAME: citybms
    DB_HOST: 192.168.111.5:27011
    CACHE_HOST: 192.168.111.149
  sxbms:
    DB_NAME: sxbms
    DB_HOST: 192.168.111.149:27019
    CACHE_HOST: 192.168.111.147

SMTP_HOST: 'smtp.exmail.qq.com'
SMTP_PORT: 25
SMTP_LOGIN: 'service@smartbow.net'
SMTP_PASSWORD: '2wsx3edc'
SMTP_FROM: 'service@smartbow.net'
